#!/usr/bin/env bash
# This script handles the secure copy of files from the local machine to the remote server

if [[ $# -ne 4 ]]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i $4 $1 $3@$2:~/
fi
