#!/usr/bin/env bash
# redirects to another page

PGREDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "30i $PGREDIRECT" /etc/nginx/sites-available/default
service nginx start
