#!/usr/bin/env bash
# creates  a custom 404 page
PGREDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
PGNOTFOUND="error_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\t\tinternal;\n}\n"
MATCH_PATTERN="#error_page 404 /404.html;"

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "30i $PGREDIRECT" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "s@$MATCH_PATTERN@$PGNOTFOUND@" /etc/nginx/sites-available/default

service nginx start
