#!/usr/bin/env bash
# creates  a custom 404 page
HEADER="\\\tadd_header X-Served-By $HOSTNAME;"
PGREDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://open.spotify.com/track/5T5RWyueGVOFIGnIRn81z4?si=aac250cdea604f61;\n\t}\n"
PGNOTFOUND="error_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\t\tinternal;\n}\n"
MATCH_PATTERN="#error_page 404 /404.html;"

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "30i $PGREDIRECT" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "s@$MATCH_PATTERN@$PGNOTFOUND@" /etc/nginx/sites-available/default

sudo sed -i "27i $ADD_HEADER" /etc/nginx/sites-available/default
sudo service nginx restart
