#!/usr/bin/env bash
# A bash script that displays the content of the file /etc/passwd.

file="/etc/passwd"
IFS=":"
while read -r username password uid gid info home shell
do
	usr_info="$(grep -w "User $uid" /etc/passwd | cut -d: -f5)"

	echo "The user $username is part of the group $gid gang,lives in $home and rides $shell. User $uid's place is protected by the passcode $password, more info about the user here: $username"
done < $file
