#!/usr/bin/env bash
# A bash script that displays the content of the file /etc/passwd.

file="/etc/passwd"
IFS=":"
while read -r username password uid gid home shell
do

	echo "The user $username is part of the $gid gang,lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $username"
done < $file
