#!/usr/bin/env bash
# This script uses an while loop to display "Best School" 10 times

i=1
while [ $i -le 10 ]
do
	if [[ $i == 9 ]]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	i=$(( i+1 ))
done
