#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

hrs=0
min=1
while [ $hrs -le 12 ]
do
	echo "Hour: $hrs"
	hrs=$(( hrs+1 ))
	while [ $min -lt 60 ]
	do
		echo "$min"
		min=$(( min+1 ))
	done
	min=1
done
